class ChatUserIdsModel {
  String? receiveUserRole;
  String? sendUserRole;
  String? lastChatTime;
  String? createdAt;
  bool? isToday;
  String? userId;
  String? sendUserId;
  String? receiveUserId;
  String? name;
  String? shortName;
  String? status;
  String? lastChatMessage;
  String? isPinnedUser;
  String? isMuted;
  bool? isActiveChat;
  int? unreadMessageCount;
  String? avatar;
  String? chats;

  ChatUserIdsModel(
      {this.receiveUserRole,
      this.sendUserRole,
      this.lastChatTime,
      this.createdAt,
      this.isToday,
      this.userId,
      this.sendUserId,
      this.receiveUserId,
      this.name,
      this.shortName,
      this.status,
      this.lastChatMessage,
      this.isPinnedUser,
      this.isMuted,
      this.isActiveChat,
      this.unreadMessageCount,
      this.avatar,
      this.chats});

  ChatUserIdsModel.fromJson(Map<String, dynamic> json) {
    receiveUserRole = json['receiveUserRole'];
    sendUserRole = json['sendUserRole'];
    lastChatTime = json['lastChatTime'];
    createdAt = json['createdAt'];
    isToday = json['isToday'];
    userId = json['userId'];
    sendUserId = json['sendUserId'];
    receiveUserId = json['receiveUserId'];
    name = json['name'];
    shortName = json['shortName'];
    status = json['status'];
    lastChatMessage = json['lastChatMessage'];
    isPinnedUser = json['isPinnedUser'];
    isMuted = json['isMuted'];
    isActiveChat = json['isActiveChat'];
    unreadMessageCount = json['unreadMessageCount'];
    avatar = json['avatar'];
    chats = json['chats'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['receiveUserRole'] = receiveUserRole;
    data['sendUserRole'] = sendUserRole;
    data['lastChatTime'] = lastChatTime;
    data['createdAt'] = createdAt;
    data['isToday'] = isToday;
    data['userId'] = userId;
    data['sendUserId'] = sendUserId;
    data['receiveUserId'] = receiveUserId;
    data['name'] = name;
    data['shortName'] = shortName;
    data['status'] = status;
    data['lastChatMessage'] = lastChatMessage;
    data['isPinnedUser'] = isPinnedUser;
    data['isMuted'] = isMuted;
    data['isActiveChat'] = isActiveChat;
    data['unreadMessageCount'] = unreadMessageCount;
    data['avatar'] = avatar;
    data['chats'] = chats;
    return data;
  }
}

/// contact list
///
class ChatContactListmodel {
  String? receiveUserRole;
  String? sendUserRole;
  String? lastChatTime;
  String? createdAt;
  bool? isToday;
  String? userId;
  String? sendUserId;
  String? receiveUserId;
  String? name;
  String? shortName;
  String? status;
  String? lastChatMessage;
  String? isPinnedUser;
  String? isMuted;
  bool? isActiveChat;
  String? unreadMessageCount;
  String? avatar;
  String? chats;

  ChatContactListmodel(
      {this.receiveUserRole,
      this.sendUserRole,
      this.lastChatTime,
      this.createdAt,
      this.isToday,
      this.userId,
      this.sendUserId,
      this.receiveUserId,
      this.name,
      this.shortName,
      this.status,
      this.lastChatMessage,
      this.isPinnedUser,
      this.isMuted,
      this.isActiveChat,
      this.unreadMessageCount,
      this.avatar,
      this.chats});

  ChatContactListmodel.fromJson(Map<String, dynamic> json) {
    receiveUserRole = json['receiveUserRole'];
    sendUserRole = json['sendUserRole'];
    lastChatTime = json['lastChatTime'];
    createdAt = json['createdAt'];
    isToday = json['isToday'];
    userId = json['userId'];
    sendUserId = json['sendUserId'];
    receiveUserId = json['receiveUserId'];
    name = json['name'];
    shortName = json['shortName'];
    status = json['status'];
    lastChatMessage = json['lastChatMessage'];
    isPinnedUser = json['isPinnedUser'];
    isMuted = json['isMuted'];
    isActiveChat = json['isActiveChat'];
    unreadMessageCount = json['unreadMessageCount'];
    avatar = json['avatar'];
    chats = json['chats'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['receiveUserRole'] = receiveUserRole;
    data['sendUserRole'] = sendUserRole;
    data['lastChatTime'] = lastChatTime;
    data['createdAt'] = createdAt;
    data['isToday'] = isToday;
    data['userId'] = userId;
    data['sendUserId'] = sendUserId;
    data['receiveUserId'] = receiveUserId;
    data['name'] = name;
    data['shortName'] = shortName;
    data['status'] = status;
    data['lastChatMessage'] = lastChatMessage;
    data['isPinnedUser'] = isPinnedUser;
    data['isMuted'] = isMuted;
    data['isActiveChat'] = isActiveChat;
    data['unreadMessageCount'] = unreadMessageCount;
    data['avatar'] = avatar;
    data['chats'] = chats;
    return data;
  }
}

// Chat screen

// class Autogenerated {
//   List<CurrentUserList>? currentUserList;

//   Autogenerated({this.currentUserList});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     if (json['currentUserList'] != null) {
//       currentUserList = <CurrentUserList>[];
//       json['currentUserList'].forEach((v) {
//         currentUserList!.add(new CurrentUserList.fromJson(v));
//       });
//     }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     if (this.currentUserList != null) {
//       data['currentUserList'] =
//           this.currentUserList!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

class CurrentUserListModel {
  String? receiveUserRole;
  String? sendUserRole;
  String? lastChatTime;
  String? createdAt;
  String? isToday;
  String? userId;
  String? sendUserId;
  String? receiveUserId;
  String? name;
  String? shortName;
  String? status;
  String? lastChatMessage;
  String? isPinnedUser;
  String? isMuted;
  String? isActiveChat;
  String? unreadMessageCount;
  String? avatar;
  List<ChatsByUserModel>? chats;

  CurrentUserListModel(
      {this.receiveUserRole,
      this.sendUserRole,
      this.lastChatTime,
      this.createdAt,
      this.isToday,
      this.userId,
      this.sendUserId,
      this.receiveUserId,
      this.name,
      this.shortName,
      this.status,
      this.lastChatMessage,
      this.isPinnedUser,
      this.isMuted,
      this.isActiveChat,
      this.unreadMessageCount,
      this.avatar,
      this.chats});

  CurrentUserListModel.fromJson(Map<String, dynamic> json) {
    receiveUserRole = json['receiveUserRole'];
    sendUserRole = json['sendUserRole'];
    lastChatTime = json['lastChatTime'];
    createdAt = json['createdAt'];
    isToday = json['isToday'];
    userId = json['userId'];
    sendUserId = json['sendUserId'];
    receiveUserId = json['receiveUserId'];
    name = json['name'];
    shortName = json['shortName'];
    status = json['status'];
    lastChatMessage = json['lastChatMessage'];
    isPinnedUser = json['isPinnedUser'];
    isMuted = json['isMuted'];
    isActiveChat = json['isActiveChat'];
    unreadMessageCount = json['unreadMessageCount'];
    avatar = json['avatar'];
    if (json['chats'] != null) {
      chats = <ChatsByUserModel>[];
      json['chats'].forEach((v) {
        chats!.add(ChatsByUserModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['receiveUserRole'] = receiveUserRole;
    data['sendUserRole'] = sendUserRole;
    data['lastChatTime'] = lastChatTime;
    data['createdAt'] = createdAt;
    data['isToday'] = isToday;
    data['userId'] = userId;
    data['sendUserId'] = sendUserId;
    data['receiveUserId'] = receiveUserId;
    data['name'] = name;
    data['shortName'] = shortName;
    data['status'] = status;
    data['lastChatMessage'] = lastChatMessage;
    data['isPinnedUser'] = isPinnedUser;
    data['isMuted'] = isMuted;
    data['isActiveChat'] = isActiveChat;
    data['unreadMessageCount'] = unreadMessageCount;
    data['avatar'] = avatar;
    if (chats != null) {
      data['chats'] = chats!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ChatsByUserModel {
  String? id;
  String? tblId;
  String? userChatId;
  bool? isReceived;
  String? sendTime;
  String? messages;
  String? messageType;

  ChatsByUserModel(
      {this.id,
      this.tblId,
      this.userChatId,
      this.isReceived,
      this.sendTime,
      this.messages,
      this.messageType});

  ChatsByUserModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    tblId = json['tblId'];
    userChatId = json['userChatId'];
    isReceived = json['isReceived'];
    sendTime = json['sendTime'];
    messages = json['messages'];
    messageType = json['messageType'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['tblId'] = tblId;
    data['userChatId'] = userChatId;
    data['isReceived'] = isReceived;
    data['sendTime'] = sendTime;
    data['messages'] = messages;
    data['messageType'] = messageType;
    return data;
  }
}
