

class Autogenerated {
  Settings? settings;
  List<SmsProviders>? smsProviders;
  bool? attedanceSummary;
  List<Null>? voiceSmsProviders;

  Autogenerated(
      {this.settings,
        this.smsProviders,
        this.attedanceSummary,
        this.voiceSmsProviders});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    settings = json['settings'] != null
        ? new Settings.fromJson(json['settings'])
        : null;
    if (json['smsProviders'] != null) {
      smsProviders = <SmsProviders>[];
      json['smsProviders'].forEach((v) {
        smsProviders!.add(new SmsProviders.fromJson(v));
      });
    }
    attedanceSummary = json['attedanceSummary'];

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.settings != null) {
      data['settings'] = this.settings!.toJson();
    }
    if (this.smsProviders != null) {
      data['smsProviders'] = this.smsProviders!.map((v) => v.toJson()).toList();
    }
    data['attedanceSummary'] = this.attedanceSummary;

    return data;
  }
}

class Settings {
  String? uploadPassword;
  bool? allowPrintLogo;
  bool? studentDualAttendance;
  bool? senDSMSTOAUTHORIZEDPERSON;
  bool? senDEMAILTOAUTHORIZEDPERSON;
  bool? smsSettingsInlcudeSenderName;
  String? smsSettingsSenderName;
  String? smsSettingsSenderPosition;
  String? smsSettingsCurrentProvider;
  String? voiceSmsSettingsCurrentProvider;
  String? allowPrintNameAddress;
  bool? showFeesWiseSummary;
  bool? applySMSFormatApproval;
  bool? allowPartialPayment;
  bool? automaticSms;
  String? successSms;
  String? chatStartTime;
  String? chatEndTime;
  String? failedSms;
  bool? updateStudentProfile;
  bool? showPublisherName;
  String? showInstallmentDueDate;
  String? part1Convertion;
  String? schoolId;
  bool? showCommunication;
  bool? textSMS;
  bool? voiceSMS;
  bool? email;
  bool? notification;

  Settings(
      {this.uploadPassword,
        this.allowPrintLogo,
        this.studentDualAttendance,
        this.senDSMSTOAUTHORIZEDPERSON,
        this.senDEMAILTOAUTHORIZEDPERSON,
        this.smsSettingsInlcudeSenderName,
        this.smsSettingsSenderName,
        this.smsSettingsSenderPosition,
        this.smsSettingsCurrentProvider,
        this.voiceSmsSettingsCurrentProvider,
        this.allowPrintNameAddress,
        this.showFeesWiseSummary,
        this.applySMSFormatApproval,
        this.allowPartialPayment,
        this.automaticSms,
        this.successSms,
        this.chatStartTime,
        this.chatEndTime,
        this.failedSms,
        this.updateStudentProfile,
        this.showPublisherName,
        this.showInstallmentDueDate,
        this.part1Convertion,
        this.schoolId,
        this.showCommunication,
        this.textSMS,
        this.voiceSMS,
        this.email,
        this.notification});

  Settings.fromJson(Map<String, dynamic> json) {
    uploadPassword = json['uploadPassword'];
    allowPrintLogo = json['allowPrintLogo'];
    studentDualAttendance = json['studentDualAttendance'];
    senDSMSTOAUTHORIZEDPERSON = json['senD_SMS_TO_AUTHORIZED_PERSON'];
    senDEMAILTOAUTHORIZEDPERSON = json['senD_EMAIL_TO_AUTHORIZED_PERSON'];
    smsSettingsInlcudeSenderName = json['smsSettingsInlcudeSenderName'];
    smsSettingsSenderName = json['smsSettingsSenderName'];
    smsSettingsSenderPosition = json['smsSettingsSenderPosition'];
    smsSettingsCurrentProvider = json['smsSettingsCurrentProvider'];
    voiceSmsSettingsCurrentProvider = json['voiceSmsSettingsCurrentProvider'];
    allowPrintNameAddress = json['allowPrintNameAddress'];
    showFeesWiseSummary = json['showFeesWiseSummary'];
    applySMSFormatApproval = json['applySMSFormatApproval'];
    allowPartialPayment = json['allowPartialPayment'];
    automaticSms = json['automaticSms'];
    successSms = json['successSms'];
    chatStartTime = json['chatStartTime'];
    chatEndTime = json['chatEndTime'];
    failedSms = json['failedSms'];
    updateStudentProfile = json['updateStudentProfile'];
    showPublisherName = json['showPublisherName'];
    showInstallmentDueDate = json['showInstallmentDueDate'];
    part1Convertion = json['part1Convertion'];
    schoolId = json['schoolId'];
    showCommunication = json['showCommunication'];
    textSMS = json['textSMS'];
    voiceSMS = json['voiceSMS'];
    email = json['email'];
    notification = json['notification'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['uploadPassword'] = this.uploadPassword;
    data['allowPrintLogo'] = this.allowPrintLogo;
    data['studentDualAttendance'] = this.studentDualAttendance;
    data['senD_SMS_TO_AUTHORIZED_PERSON'] = this.senDSMSTOAUTHORIZEDPERSON;
    data['senD_EMAIL_TO_AUTHORIZED_PERSON'] = this.senDEMAILTOAUTHORIZEDPERSON;
    data['smsSettingsInlcudeSenderName'] = this.smsSettingsInlcudeSenderName;
    data['smsSettingsSenderName'] = this.smsSettingsSenderName;
    data['smsSettingsSenderPosition'] = this.smsSettingsSenderPosition;
    data['smsSettingsCurrentProvider'] = this.smsSettingsCurrentProvider;
    data['voiceSmsSettingsCurrentProvider'] =
        this.voiceSmsSettingsCurrentProvider;
    data['allowPrintNameAddress'] = this.allowPrintNameAddress;
    data['showFeesWiseSummary'] = this.showFeesWiseSummary;
    data['applySMSFormatApproval'] = this.applySMSFormatApproval;
    data['allowPartialPayment'] = this.allowPartialPayment;
    data['automaticSms'] = this.automaticSms;
    data['successSms'] = this.successSms;
    data['chatStartTime'] = this.chatStartTime;
    data['chatEndTime'] = this.chatEndTime;
    data['failedSms'] = this.failedSms;
    data['updateStudentProfile'] = this.updateStudentProfile;
    data['showPublisherName'] = this.showPublisherName;
    data['showInstallmentDueDate'] = this.showInstallmentDueDate;
    data['part1Convertion'] = this.part1Convertion;
    data['schoolId'] = this.schoolId;
    data['showCommunication'] = this.showCommunication;
    data['textSMS'] = this.textSMS;
    data['voiceSMS'] = this.voiceSMS;
    data['email'] = this.email;
    data['notification'] = this.notification;
    return data;
  }
}

class SmsProviders {
  String? value;
  String? text;
  bool? selected;
  bool? active;
  String? order;

  SmsProviders({this.value, this.text, this.selected, this.active, this.order});

  SmsProviders.fromJson(Map<String, dynamic> json) {
    value = json['value'];
    text = json['text'];
    selected = json['selected'];
    active = json['active'];
    order = json['order'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['value'] = this.value;
    data['text'] = this.text;
    data['selected'] = this.selected;
    data['active'] = this.active;
    data['order'] = this.order;
    return data;
  }
}
